all: 
	mkdir bin
	g++ ./1/main_1.cpp  ./1/1.cpp -o ./bin/1
	g++ ./2/main_2.cpp  ./2/2.cpp -o ./bin/2a
	g++ ./2/main_2b.cpp  ./2/2b.cpp -o ./bin/2b
	g++ ./3/3.cpp  -o ./bin/3

clean:
	rm -r ./bin